language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -r requirements.txt
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: celjgLaaqSBv7fJLhioAr3U3WA+n7HE88P13QA6DPl/rQLQu9xwZquMTBOlHi3XAm6UEQ/72bXe+JAKQPYyLewMdBlX8cJyTeoCI0zdKf/xgp0LWYcZQVrBklAM5Hw1PRKbsDp5xmtKFWoZXfvZOxTIZRSAay0WXU8rF5OSgI7aPDRzTmW23E/aJksRL3WGlUKYCFnZFkpC2EBYasuphpMTXNZAYVF4Pdb+OhPVmmm0A+ufaXskqQ2DkAcgDpUXsgfGq0Hq0mN3MXPyEGCqbyhW4rDiWkQUSvOJNZw3FxFhkhSU/5EKVgMa0b1Pz7F6PSpH6nsWrMDDQc5ZE8Kk/KkG5/mgiBgykfdFF85huxim3RO/R9mTyq2zxHwot4cTa/lWeZ0fW+Nk/BRmNINgsHiwrCWskK7103fCWNW+OwYpXuK4qkr2nzpgoS919TzxDih+GBzPonfcyxkuzIFRFwPl27u2Lb1ADEC6Vnz2v+xyrRC8Fz04DOznlsLOTJlFEyMNVIMvCni3tihSa5stmbcK+wEilkPdBv/eXYvB+K3P19tr3f6sFAPTCl36b9u7YwNcs61RHr3I2mR/rYoUS+e9HdXmj8oiCpboSU8kKrgjQwtCFuajFilqjAPDiNJZ5uJZnTMWpGoDlgOmc8WawMomLMzgp3tfszYdDrB/Z7Lk=
  on:
    tags: true
    repo: whatnick/python_dynamodb_lock
    python: 3.6
